SET IDENTITY_INSERT [dbo].[Category] ON
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (1, N'Education')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (2, N'Health')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (3, N'Transport')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (4, N'Safety & Security')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (5, N'Entertainment')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (6, N'Consumption')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (7, N'Disposal')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (8, N'Environmental Performance')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (9, N'Local Economy')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (10, N'Biodiversity')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (11, N'Communication & Social Connectivity')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (12, N'Governance')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (13, N'Well-Being Services')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (14, N'Shelter')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (15, N'Psychological Well-Being')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (16, N'Emotional Well-Being')
INSERT INTO [dbo].[Category] ([CategoryID], [Category]) VALUES (17, N'Recognition')
SET IDENTITY_INSERT [dbo].[Category] OFF
