SET IDENTITY_INSERT [dbo].[Sub_Category] ON
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (1, N'Nusery', 1)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (2, N'Primary School', 1)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (3, N'Secondary', 1)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (4, N'College', 1)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (5, N'University', 1)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (6, N'Hospital', 2)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (7, N'Doctor', 2)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (8, N'Pharmacy', 2)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (9, N'Optician', 2)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (10, N'Veterinary', 2)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (11, N'Dentist', 2)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (12, N'Bus Stops', 3)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (13, N'Train Station', 3)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (14, N'Taxi Rank', 3)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (15, N'Parking', 3)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (16, N'Police Station', 4)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (17, N'Court', 4)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (20, N'Fire Station', 4)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (21, N'Cinema', 5)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (23, N'Bowling', 5)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (24, N'Airport', 3)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (25, N'Ferry Point', 3)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (26, N'Bicycle Docking Station', 3)
INSERT INTO [dbo].[Sub_Category] ([SubCategoryID], [SubCategory], [CategoryID]) VALUES (27, N'Care Homes', 2)
SET IDENTITY_INSERT [dbo].[Sub_Category] OFF
