CREATE TABLE [dbo].[BRE_User] (
    [UserID]           INT           IDENTITY (1, 1) NOT NULL,
    [Firstname]        VARCHAR (50)  NOT NULL,
    [Surname]          VARCHAR (50)  NOT NULL,
    [Gender]           VARCHAR (MAX) NOT NULL,
    [DateOfBirth]      DATE          NOT NULL,
    [Email]            VARCHAR (MAX) NOT NULL,
    [Username]         VARCHAR (50)  NOT NULL,
    [Password]         VARCHAR (50)  NOT NULL,
    [HouseNumber/Name] VARCHAR (MAX) NULL,
    [Address]          VARCHAR (MAX) NULL,
    [Town]             VARCHAR (MAX) NULL,
    [Postcode]         VARCHAR (7)   NULL,
    [Category_1]       INT           NOT NULL,
    [Category_2]       INT           NOT NULL,
    [Category_3]       INT           NOT NULL,
    [Category_4]       INT           NOT NULL,
    [Category_5]       INT           NOT NULL,
    [Category_6]       INT           NOT NULL,
    [Category_7]       INT           NOT NULL,
    [Category_8]       INT           NOT NULL,
    [Category_9]       INT           NOT NULL,
    [Category_10]      INT           NOT NULL,
    [Category_11]      INT           NOT NULL,
    [Category_12]      INT           NOT NULL,
    [Category_13]      INT           NOT NULL,
    [Category_14]      INT           NOT NULL,
    [Category_15]      INT           NOT NULL,
    [Category_16]      INT           NOT NULL
);

